In [1]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [3]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [4]:
df.shape

(100, 3)

In [6]:
df.head()

,feature1,feature2,target
0,-0.161953,-2.468059,-256.051318
1,0.175666,-0.519319,-43.999562
2,-0.950590,0.949101,63.630979
3,0.013810,0.222672,13.573392
4,-0.204551,0.440438,-67.975767


In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred = lr.predict(X_test)

In [14]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 30.62882870672998
MSE 1574.3000572611465
R2 score 0.8222926676603733


In [15]:
lr.coef_

array([49.2641758 , 84.18680767])

In [16]:
lr.intercept_

-8.34974400030887

In [17]:
X_test[0:1]

array([[-0.43369128, -1.67820459]])

In [19]:
y_test[0:1]

array([-172.83523109])

In [18]:
49.2641758*-0.43369128 + 84.18680767*-1.67820459 -8.34974400030887

-170.99787451039708

In [20]:
y_pred[0:1]

array([-170.99787427])